

DROP TABLE IF EXISTS STATUS; 

-- ORDER OF TABLE CREATION : MANAGER -> TEAM -> TEAM_MEMBERS -> TRAINING , TOURNAMENTS -> REFEREES -> VENUE -> MATCHES +RESULTS -> POINTS_TABLE
CREATE TABLE INFO (
Username TEXT NOT NULL  ,
Password TEXT NOT NULL,
SALARY INTEGER,
AGE INTEGER NOT NULL,
EMAIL TEXT NOT NULL
); 
CREATE TABLE STATUS (
NAME TEXT NOT NULL  ,
CNIC TEXT NOT NULL,
MOBILENUMBER TEXT NOT NULL,
); 




